// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'eu-central-1:8ed359a1-d67b-400d-9c54-49f8d1d200c0',
    'aws_cognito_region': 'eu-central-1',
    'aws_mobile_analytics_app_id': '2ac14de32e2041ae93f439c35c291d50',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7a21ac39-0594-4af3-9b5c-0b7d0000ca33',
    'aws_project_name': 'BuzzOut',
    'aws_project_region': 'eu-central-1',
    'aws_resource_name_prefix': 'buzzout-mobilehub-922900175',
}

export default awsmobile;
